name: Maven Build

on:
  push:
    paths:
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'
  pull_request:
    paths:
      - '.mvn/wrapper/**'
      - 'pom.xml'
      - 'src/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Setup Testcontainers Cloud Client
        uses: atomicjar/testcontainers-cloud-setup-action@v1
        with:
          token: ${{ secrets.TC_CLOUD_TOKEN }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
